AWSTemplateFormatVersion: '2010-09-09'
Description: Use Fargate and Lambdas to launch a dockerized tutorial

Parameters:
  TutorialImage:
    Type: String
    Description: Docker image with tutorial materials
  TutorialName:
    Type: String
    Description: Name of the tutorial
  TutorialPort:
    Type: Number
    Description: Port to expose in docker
  TutorialQueryString:
    Type: String
    Description: Query string to append to the container URL
    Default: ""
  TaskTimeoutHours:
    Type: Number
    Description: Maximum hours a task can run before being stopped
    Default: 6
    MinValue: 1
    MaxValue: 72

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub "${TutorialName}-Vpc"

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub "${TutorialName}-PublicSubnet"

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${TutorialName}-cluster"

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${TutorialName}-task"
      Cpu: '4096'
      Memory: '8192'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: !Sub "${TutorialName}-container"
          Image: !Ref TutorialImage
          PortMappings:
            - ContainerPort: !Ref TutorialPort
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub "/ecs/${TutorialName}-task"
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: ecs
          Environment:
            - Name: LAST_UPDATED
              Value: "2025-06-26-v1"

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${TutorialName}-task"
      RetentionInDays: 7

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow port access
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref TutorialPort
          ToPort: !Ref TutorialPort
          CidrIp: 0.0.0.0/0

  SlackBotLaunchLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-SlackBotLaunch"
      Handler: launch-function.lambda_handler
      Runtime: python3.12
      Role: !GetAtt SlackBotLambdaRole.Arn
      Timeout: 15
      Code:
        S3Bucket: hpcic-tutorials
        S3Key: slackbot/launch-function.zip
        S3ObjectVersion: "zu9ciBH_TvdFfW0PkTpQ6WsRlF8W6gTq"

  SlackBotNotifyLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-SlackBotNotify"
      Handler: notify-function.lambda_handler
      Runtime: python3.12
      Role: !GetAtt SlackBotLambdaRole.Arn
      Timeout: 500
      Code:
        S3Bucket: hpcic-tutorials
        S3Key: slackbot/notify-function.zip
        S3ObjectVersion: "l2IecZmSLSJFRylbzMmDZTbgnOs4sLaC"

  SlackBotEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "${AWS::StackName}-SlackBotTaskReady"
      EventBusName: default
      EventPattern:
        source:
          - "custom.slackbot"
        detail:
          stack:
            - !Sub "${AWS::StackName}"
      Targets:
        - Arn: !GetAtt SlackBotNotifyLambda.Arn
          Id: SlackNotify

  SlackBotNotifyPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SlackBotNotifyLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt SlackBotEventRule.Arn

  SlackBotLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-SlackBotLambdaExecutionRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SlackBotPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                  - events:PutEvents
                Resource:
                  - !Sub arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${AWS::StackName}/*
                  - !Sub arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/default
              - Effect: Allow
                Action:
                  - ecs:RunTask
                  - ecs:DescribeTasks
                  - ec2:DescribeNetworkInterfaces
                  - ecs:TagResource
                Resource: "*"
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: !GetAtt TaskExecutionRole.Arn

  SlackHttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: SlackBotAPI
      ProtocolType: HTTP

  SlackHttpApiIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref SlackHttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt SlackBotLaunchLambda.Arn
      PayloadFormatVersion: "2.0"

  SlackHttpApiRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref SlackHttpApi
      RouteKey: "POST /launch/{stack_name}"
      Target: !Sub "integrations/${SlackHttpApiIntegration}"

  SlackHttpApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref SlackHttpApi
      StageName: $default
      AutoDeploy: true

  SlackBotLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SlackBotLaunchLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${SlackHttpApi}/*/*"

  SlackBotNotifyLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${SlackBotNotifyLambda}"
      RetentionInDays: 7

  SlackBotLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${SlackBotLaunchLambda}"
      RetentionInDays: 7

  CleanupLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-TaskCleanup"
      Handler: cleanup-tasks-function.lambda_handler
      Runtime: python3.12
      Role: !GetAtt CleanupLambdaRole.Arn
      Timeout: 300
      Code:
        S3Bucket: hpcic-tutorials
        S3Key: slackbot/cleanup-tasks-function.zip
        S3ObjectVersion: "PLACEHOLDER"

  CleanupLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-CleanupLambdaRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CleanupPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - ecs:ListTasks
                  - ecs:DescribeTasks
                  - ecs:StopTask
                Resource: "*"

  CleanupScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "${AWS::StackName}-TaskCleanupSchedule"
      Description: "Triggers task cleanup every hour"
      ScheduleExpression: "rate(1 hour)"
      Targets:
        - Arn: !GetAtt CleanupLambda.Arn
          Id: CleanupTarget
          Input: !Sub |
            {
              "cluster_name": "${Cluster}",
              "timeout_hours": ${TaskTimeoutHours}
            }

  CleanupLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref CleanupLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt CleanupScheduleRule.Arn

  CleanupLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${CleanupLambda}"
      RetentionInDays: 7

Outputs:
  ClusterName:
    Description: ECS Cluster Name
    Value: !Ref Cluster

  TaskDefinitionArn:
    Description: Task Definition ARN
    Value: !Ref TaskDefinition

  SecurityGroupId:
    Description: Security Group ID
    Value: !Ref SecurityGroup

  PublicSubnetId:
    Description: Public Subnet ID
    Value: !Ref PublicSubnet

  TutorialPort:
    Description: Port exposed by the container
    Value: !Ref TutorialPort

  TutorialQueryString:
    Description: Query string to append to the container URL
    Value: !Ref TutorialQueryString

  RunTaskCommandTemplate:
    Description: Template for launching a tutorial task
    Value: !Sub |

      COUNT=$(aws ecs list-tasks \
        --cluster ${Cluster} \
        --desired-status RUNNING \
        --query 'taskArns' \
        --output text | wc -w)
      TASK_ID=$(printf "task-%03d" $((COUNT + 1)))

      aws ecs run-task \
        --cluster ${Cluster} \
        --launch-type FARGATE \
        --task-definition ${TaskDefinition} \
        --network-configuration "awsvpcConfiguration={subnets=[${PublicSubnet}],securityGroups=[${SecurityGroup}],assignPublicIp=ENABLED}" \
        --tags key=task-id,value=$TASK_ID key=launch-type,value=cli

  LaunchMultipleTasksCommand:
    Description: Bash function to launch N tutorial tasks through CLI
    Value: !Sub |
      launch_tasks() {
        local N=$1
        if [ -z "$N" ]; then
          echo "Usage: launch_tasks <number-of-tasks>"
          return 1
        fi

        for ((i = 1; i <= N; i++)); do
          TASK_ID=$(printf "task-%03d" $i)
          echo "Launching $TASK_ID..."

          aws ecs run-task \
            --cluster ${Cluster} \
            --launch-type FARGATE \
            --task-definition ${TaskDefinition} \
            --network-configuration "awsvpcConfiguration={subnets=[${PublicSubnet}],securityGroups=[${SecurityGroup}],assignPublicIp=ENABLED}" \
            --tags key=task-id,value=$TASK_ID key=launch-type,value=cli
        done
      }

      echo "Run 'launch_tasks N' to launch N tasks."

  GetContainerIPCommand:
    Description: Print task-id and public IP for all running tasks
    Value: !Sub |
      echo "task-id,public-ip"

      aws ecs list-tasks \
        --cluster ${Cluster} \
        --desired-status RUNNING \
        --query 'taskArns[]' \
        --output text | tr '\t' '\n' | while read TASK; do

        TASK_ID=$(aws ecs list-tags-for-resource \
          --resource-arn "$TASK" \
          --query 'tags[?key==`task-id`].value' \
          --output text)

        ENI_ID=$(aws ecs describe-tasks \
          --cluster ${Cluster} \
          --tasks "$TASK" \
          --query 'tasks[0].attachments[0].details[?name==`networkInterfaceId`].value' \
          --output text)

        PUBLIC_IP=$(aws ec2 describe-network-interfaces \
          --network-interface-ids "$ENI_ID" \
          --query 'NetworkInterfaces[0].Association.PublicIp' \
          --output text)

        echo "$TASK_ID,$PUBLIC_IP"
      done

  GetCLITaskIPCommand:
    Description: Print task-id and public IP for tasks launched through CLI only
    Value: !Sub |
      echo "task-id,public-ip"

      aws ecs list-tasks \
        --cluster ${Cluster} \
        --desired-status RUNNING \
        --query 'taskArns[]' \
        --output text | tr '\t' '\n' | while read TASK; do

        # Check if task has cli launch tag
        LAUNCH_TYPE=$(aws ecs list-tags-for-resource \
          --resource-arn "$TASK" \
          --query 'tags[?key==`launch-type`].value' \
          --output text)

        if [ "$LAUNCH_TYPE" = "cli" ]; then
          TASK_ID=$(aws ecs list-tags-for-resource \
            --resource-arn "$TASK" \
            --query 'tags[?key==`task-id`].value' \
            --output text)

          ENI_ID=$(aws ecs describe-tasks \
            --cluster ${Cluster} \
            --tasks "$TASK" \
            --query 'tasks[0].attachments[0].details[?name==`networkInterfaceId`].value' \
            --output text)

          PUBLIC_IP=$(aws ec2 describe-network-interfaces \
            --network-interface-ids "$ENI_ID" \
            --query 'NetworkInterfaces[0].Association.PublicIp' \
            --output text)

          echo "$TASK_ID,$PUBLIC_IP"
        fi
      done

  CleanupCommand:
    Description: Stop all tutorial tasks
    Value: !Sub |

      aws ecs list-tasks --cluster ${Cluster} --desired-status RUNNING --query 'taskArns[]' --output text | \
      xargs -n 1 -I {} aws ecs stop-task --cluster ${Cluster} --task {}

  SlackCommandUrl:
    Description: Slack command endpoint URL
    Value: !Sub "https://${SlackHttpApi}.execute-api.${AWS::Region}.amazonaws.com/launch/${AWS::StackName}"
